export { default as EventsPanel } from './EventsPanel'
export { default as AlertsPanel } from './AlertsPanel'
export { default as AssetsPanel } from './AssetsPanel'
export { default as DetectionPanel } from './DetectionPanel'
export { default as SystemPanel } from './SystemPanel'
